---
- hosts: localhost
  
  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        region: "{{ region }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_group: default
        network:
          assign_public_ip: true
        image_id: "{{ image_id }}"
        state: running
      register: ec2_instance_output

    - name: Wait for SSH to start
      ansible.builtin.wait_for:
        host: "{{ ec2_instance_output.instances.0.public_ip_address }}"
        port: 22
        search_regex: OpenSSH

    - name: Display EC2 instance
      ansible.builtin.debug:
        msg: "EC2 instance created. Use 'ssh ec2-user@{{ ec2_instance_output.instances.0.public_dns_name }}' to access it"
